// Quick-start templates so users don't start from a blank page. Small, sensible
// topologies they can load and then tweak.

export const TEMPLATES = [
  {
    key: 'home',
    label: 'Home Office',
    net: {
      meta: { name: 'Home Network' },
      zones: [
        { id: 'edge', label: 'Internet', color: '#ff5a5a' },
        { id: 'lan', label: 'Home Network', color: '#5af0c0' },
      ],
      nodes: [
        { id: 'net', label: 'Internet', type: 'internet', zone: 'edge', status: 'ok' },
        { id: 'gw', label: 'Router / Firewall', type: 'router', zone: 'edge', status: 'ok' },
        { id: 'sw', label: 'Switch', type: 'switch', zone: 'lan', status: 'ok' },
        { id: 'ap', label: 'Wi-Fi Access Point', type: 'ap', zone: 'lan', status: 'ok' },
        { id: 'pc1', label: 'Desktop PC', type: 'workstation', zone: 'lan', status: 'ok' },
        { id: 'lap1', label: 'Laptop', type: 'laptop', zone: 'lan', status: 'ok' },
        { id: 'phone', label: 'Smartphone', type: 'mobile', zone: 'lan', status: 'ok' },
        { id: 'nas', label: 'NAS Storage', type: 'nas', zone: 'lan', status: 'ok' },
        { id: 'printer', label: 'Printer', type: 'printer', zone: 'lan', status: 'ok' },
      ],
      links: [
        { source: 'net', target: 'gw' },
        { source: 'gw', target: 'sw' },
        { source: 'sw', target: 'ap' },
        { source: 'sw', target: 'pc1' },
        { source: 'sw', target: 'nas' },
        { source: 'sw', target: 'printer' },
        { source: 'ap', target: 'lap1' },
        { source: 'ap', target: 'phone' },
      ],
    },
  },
  {
    key: 'smb',
    label: 'Small Business',
    net: {
      meta: { name: 'Small Business Network' },
      zones: [
        { id: 'edge', label: 'Perimeter', color: '#ff5a5a' },
        { id: 'dmz', label: 'DMZ', color: '#ffb454' },
        { id: 'core', label: 'Core', color: '#54a0ff' },
        { id: 'lan', label: 'Office LAN', color: '#5af0c0' },
        { id: 'cloud', label: 'Cloud', color: '#a98bff' },
      ],
      nodes: [
        { id: 'inet', label: 'Internet', type: 'internet', zone: 'edge', status: 'ok' },
        { id: 'fw', label: 'Firewall', type: 'firewall', zone: 'edge', status: 'ok' },
        { id: 'web', label: 'Web Server', type: 'webserver', zone: 'dmz', status: 'ok' },
        { id: 'mail', label: 'Mail Server', type: 'mail', zone: 'dmz', status: 'ok' },
        { id: 'coresw', label: 'Core Switch', type: 'switch', zone: 'core', status: 'ok' },
        { id: 'accsw', label: 'Access Switch', type: 'switch', zone: 'core', status: 'ok' },
        { id: 'ap1', label: 'Wi-Fi AP', type: 'ap', zone: 'core', status: 'ok' },
        { id: 'ad', label: 'Domain Controller', type: 'directory', zone: 'lan', status: 'ok' },
        { id: 'file', label: 'File Server', type: 'nas', zone: 'lan', status: 'ok' },
        { id: 'db', label: 'Database', type: 'database', zone: 'lan', status: 'ok' },
        { id: 'app', label: 'App Server', type: 'appserver', zone: 'lan', status: 'ok' },
        { id: 'pc1', label: 'Workstation 1', type: 'workstation', zone: 'lan', status: 'ok' },
        { id: 'pc2', label: 'Workstation 2', type: 'workstation', zone: 'lan', status: 'ok' },
        { id: 'pc3', label: 'Workstation 3', type: 'workstation', zone: 'lan', status: 'ok' },
        { id: 'pc4', label: 'Workstation 4', type: 'workstation', zone: 'lan', status: 'warning' },
        { id: 'printer', label: 'Printer', type: 'printer', zone: 'lan', status: 'ok' },
        { id: 'm365', label: 'Microsoft 365', type: 'saas', zone: 'cloud', status: 'ok' },
      ],
      links: [
        { source: 'inet', target: 'fw' },
        { source: 'fw', target: 'web' },
        { source: 'fw', target: 'mail' },
        { source: 'fw', target: 'coresw' },
        { source: 'coresw', target: 'accsw' },
        { source: 'accsw', target: 'ap1' },
        { source: 'coresw', target: 'ad' },
        { source: 'coresw', target: 'file' },
        { source: 'coresw', target: 'db' },
        { source: 'coresw', target: 'app' },
        { source: 'accsw', target: 'pc1' },
        { source: 'accsw', target: 'pc2' },
        { source: 'accsw', target: 'pc3' },
        { source: 'accsw', target: 'pc4' },
        { source: 'accsw', target: 'printer' },
        { source: 'fw', target: 'm365' },
      ],
    },
  },
];
